run:
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - depguard
    - dogsled
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - misspell
    - unconvert
    # default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 60
  depguard:
    rules:
      main:
        deny:
          - pkg: golang.org/x/net/context
            desc: use standard library context
          - pkg: github.com/prometheus/common/log
            desc: use log/slog

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    # Generated code may have long functions
    - path: client_gen_.*\.go
      linters:
        - funlen
        - goconst
        - dupl
