package wecom

func init() {
	registerClientAPIPath("/cgi-bin/wedrive/file_acl_add", "AddFileMember", cRef.AddFileMember)
	registerClientAPIPath("/cgi-bin/wedrive/file_acl_del", "DeleteMemberAcl", cRef.DeleteMemberAcl)
	registerClientAPIPath("/cgi-bin/wedrive/file_create", "CreateFile", cRef.CreateFile)
	registerClientAPIPath("/cgi-bin/wedrive/file_delete", "DeleteFile", cRef.DeleteFile)
	registerClientAPIPath("/cgi-bin/wedrive/file_download", "DownloadFile", cRef.DownloadFile)
	registerClientAPIPath("/cgi-bin/wedrive/file_info", "GetDriveFileInfo", cRef.GetDriveFileInfo)
	registerClientAPIPath("/cgi-bin/wedrive/file_list", "ListDriveFile", cRef.ListDriveFile)
	registerClientAPIPath("/cgi-bin/wedrive/file_move", "MoveFile", cRef.MoveFile)
	registerClientAPIPath("/cgi-bin/wedrive/file_rename", "RenameFile", cRef.RenameFile)
	registerClientAPIPath("/cgi-bin/wedrive/file_secure_setting", "UpdateFileSecureSetting", cRef.UpdateFileSecureSetting)
	registerClientAPIPath("/cgi-bin/wedrive/file_setting", "SetFileShareSetting", cRef.SetFileShareSetting)
	registerClientAPIPath("/cgi-bin/wedrive/file_share", "GetFileShareUrl", cRef.GetFileShareUrl)
	registerClientAPIPath("/cgi-bin/wedrive/file_upload", "UploadFile", cRef.UploadFile)
	registerClientAPIPath("/cgi-bin/wedrive/file_upload_init", "InitWedriveFileUpload", cRef.InitWedriveFileUpload)
	registerClientAPIPath("/cgi-bin/wedrive/get_file_permission", "GetFilePermission", cRef.GetFilePermission)
	registerClientAPIPath("/cgi-bin/wedrive/mng_pro_info", "GetWeDriveProInfo", cRef.GetWeDriveProInfo)
	registerClientAPIPath("/cgi-bin/wedrive/new_space_info", "GetSpaceInfo", cRef.GetSpaceInfo)
	registerClientAPIPath("/cgi-bin/wedrive/space_acl_add", "AddSpaceMemberDepartment", cRef.AddSpaceMemberDepartment)
	registerClientAPIPath("/cgi-bin/wedrive/space_acl_del", "RemoveSpaceMemberOrDept", cRef.RemoveSpaceMemberOrDept)
	registerClientAPIPath("/cgi-bin/wedrive/space_create", "CreateSpace", cRef.CreateSpace)
	registerClientAPIPath("/cgi-bin/wedrive/space_dismiss", "DismissSpace", cRef.DismissSpace)
	registerClientAPIPath("/cgi-bin/wedrive/space_rename", "RenameSpace", cRef.RenameSpace)
	registerClientAPIPath("/cgi-bin/wedrive/space_setting", "UpdateSpaceSetting", cRef.UpdateSpaceSetting)
	registerClientAPIPath("/cgi-bin/wedrive/space_share", "GetSpaceShareLink", cRef.GetSpaceShareLink)
	registerClientAPIPath("/cgi-bin/wedrive/vip/batch_add", "BatchAddDriveVip", cRef.BatchAddDriveVip)
	registerClientAPIPath("/cgi-bin/wedrive/vip/batch_del", "BatchDelDriveVip", cRef.BatchDelDriveVip)
	registerClientAPIPath("/cgi-bin/wedrive/vip/list", "ListDriveVip", cRef.ListDriveVip)
}
