name: CI
on: [push, pull_request]

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Check go mod
        run: |
          go version
          go mod tidy
          git diff --exit-code go.mod

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.7.2

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Test
        run: |
          go version
          go test ./wecom/ -v -count=1
      - name: Build
        run: go build ./...
      - name: Run CI
        run: make ci
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v4
